disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace
- identifier_name
- opening_brace
- closure_parameter_position
- switch_case_alignment
- statement_position
- vertical_whitespace
- multiple_closures_with_trailing_closure

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods

